### ISSUE TITLE
lookupAllTimes conccurency launch some errors in HeapMemoeySegment

### ISSUE THREAD

**Issue by jejemontagne** [kevoree-modeling/framework#2]
The issue  seams to be caused by an -1 index.

![screen shot 2015-07-24 at 11 50 21](https://cloud.githubusercontent.com/assets/6117317/8876610/0be90ca6-3221-11e5-82d0-35a4771d6551.png)

java.lang.NullPointerException
    at org.kevoree.modeling.memory.struct.segment.impl.HeapMemorySegment.init(HeapMemorySegment.java:184)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager.internal_unserialize(MemoryManager.java:786)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager.access$700(MemoryManager.java:27)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager$10.on(MemoryManager.java:762)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager$10.on(MemoryManager.java:756)
    at org.kevoree.modeling.drivers.leveldb.LevelDbContentDeliveryDriver.get(LevelDbContentDeliveryDriver.java:94)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager.bumpKeysToCache(MemoryManager.java:756)
    at org.kevoree.modeling.memory.manager.impl.LookupAllTimesRunnable$1$2.on(LookupAllTimesRunnable.java:78)
    at org.kevoree.modeling.memory.manager.impl.LookupAllTimesRunnable$1$2.on(LookupAllTimesRunnable.java:62)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager$10.on(MemoryManager.java:770)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager$10.on(MemoryManager.java:756)
    at org.kevoree.modeling.drivers.leveldb.LevelDbContentDeliveryDriver.get(LevelDbContentDeliveryDriver.java:94)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager.bumpKeysToCache(MemoryManager.java:756)
    at org.kevoree.modeling.memory.manager.impl.LookupAllTimesRunnable$1.on(LookupAllTimesRunnable.java:62)
    at org.kevoree.modeling.memory.manager.impl.LookupAllTimesRunnable$1.on(LookupAllTimesRunnable.java:35)
    at org.kevoree.modeling.memory.manager.impl.MemoryManager.bumpKeyToCache(MemoryManager.java:706)
    at org.kevoree.modeling.memory.manager.impl.LookupAllTimesRunnable.run(LookupAllTimesRunnable.java:35)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by dukeboard** [comment]
solved in current version
